Feature/add reviews and calculated rating
DigitalKampong/dk-api pull request #36
Opened 2021-01-05 16:47 UTC by zatkiller

Updated Reviews Constraint, use JWT user id, updated docs and implemented error handling

2021-01-06 07:25 UTC, ivantjh requested changes

2021-01-06 07:25 UTC, ivantjh commented on src/controllers/reviewController.ts
> +    const token = req.header('x-auth-token');
The decoding is already done in the `auth` middleware. Just need to do
```typescript
try {
    const review = await Review.create({ ...req.body, userId: req.userId, stallId: req.params.Id })
    res.status(201).json(review);
} catch(err) {
    ....
}
```

2021-01-06 07:25 UTC, ivantjh commented on src/controllers/reviewController.ts
> +    const token = req.header('x-auth-token');
`userId` is already in req -> no need decode again

2021-01-06 07:25 UTC, ivantjh commented on src/middleware/class/class.ts
> +export class JWTPayload {
Can remove this, the exact same interface is available as `UserDecoded` in `auth.ts`

2021-01-06 07:25 UTC, ivantjh commented on package.json
> +    "jwt-decode": "^3.1.2",
No need additional library, `jwt.verify` already provides the decode. Can remove

2021-01-08 04:41 UTC, wenhaogoh approved these changes
LGTM

2021-01-08 12:31 UTC, merged